apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-manager-secret
  annotations:
    kubernetes.io/service-account.name: argocd-manager
type: kubernetes.io/service-account-token
