// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/argoproj/argo-cd/v3/pkg/apiclient/applicationset (interfaces: ApplicationSetServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=argocd_applicationset.go -package=mocks github.com/argoproj/argo-cd/v3/pkg/apiclient/applicationset ApplicationSetServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	applicationset "github.com/argoproj/argo-cd/v3/pkg/apiclient/applicationset"
	v1alpha1 "github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockApplicationSetServiceClient is a mock of ApplicationSetServiceClient interface.
type MockApplicationSetServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationSetServiceClientMockRecorder
	isgomock struct{}
}

// MockApplicationSetServiceClientMockRecorder is the mock recorder for MockApplicationSetServiceClient.
type MockApplicationSetServiceClientMockRecorder struct {
	mock *MockApplicationSetServiceClient
}

// NewMockApplicationSetServiceClient creates a new mock instance.
func NewMockApplicationSetServiceClient(ctrl *gomock.Controller) *MockApplicationSetServiceClient {
	mock := &MockApplicationSetServiceClient{ctrl: ctrl}
	mock.recorder = &MockApplicationSetServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationSetServiceClient) EXPECT() *MockApplicationSetServiceClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockApplicationSetServiceClient) Create(ctx context.Context, in *applicationset.ApplicationSetCreateRequest, opts ...grpc.CallOption) (*v1alpha1.ApplicationSet, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*v1alpha1.ApplicationSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockApplicationSetServiceClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApplicationSetServiceClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockApplicationSetServiceClient) Delete(ctx context.Context, in *applicationset.ApplicationSetDeleteRequest, opts ...grpc.CallOption) (*applicationset.ApplicationSetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*applicationset.ApplicationSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockApplicationSetServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApplicationSetServiceClient)(nil).Delete), varargs...)
}

// Generate mocks base method.
func (m *MockApplicationSetServiceClient) Generate(ctx context.Context, in *applicationset.ApplicationSetGenerateRequest, opts ...grpc.CallOption) (*applicationset.ApplicationSetGenerateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Generate", varargs...)
	ret0, _ := ret[0].(*applicationset.ApplicationSetGenerateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockApplicationSetServiceClientMockRecorder) Generate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockApplicationSetServiceClient)(nil).Generate), varargs...)
}

// Get mocks base method.
func (m *MockApplicationSetServiceClient) Get(ctx context.Context, in *applicationset.ApplicationSetGetQuery, opts ...grpc.CallOption) (*v1alpha1.ApplicationSet, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*v1alpha1.ApplicationSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApplicationSetServiceClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApplicationSetServiceClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockApplicationSetServiceClient) List(ctx context.Context, in *applicationset.ApplicationSetListQuery, opts ...grpc.CallOption) (*v1alpha1.ApplicationSetList, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*v1alpha1.ApplicationSetList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockApplicationSetServiceClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApplicationSetServiceClient)(nil).List), varargs...)
}

// ResourceTree mocks base method.
func (m *MockApplicationSetServiceClient) ResourceTree(ctx context.Context, in *applicationset.ApplicationSetTreeQuery, opts ...grpc.CallOption) (*v1alpha1.ApplicationSetTree, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResourceTree", varargs...)
	ret0, _ := ret[0].(*v1alpha1.ApplicationSetTree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResourceTree indicates an expected call of ResourceTree.
func (mr *MockApplicationSetServiceClientMockRecorder) ResourceTree(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceTree", reflect.TypeOf((*MockApplicationSetServiceClient)(nil).ResourceTree), varargs...)
}
