name: lint

permissions:
  contents: read

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ⬇️ lint markdown files # Lints all markdown (.md) files
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.json'
          args: '*.md docs/*.md .github/**/*.md'
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make get-deps
      - run: go mod tidy -diff
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.64.7
